services:
  ipca-frontend:
    container_name: ipca-frontend
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        VITE_IPCA_API: ${VITE_IPCA_API}
        VITE_IPCA_RT: ${VITE_IPCA_RT}
        VITE_IPCA_MINIO: ${VITE_IPCA_MINIO}
    restart: unless-stopped
    environment:
      - TZ=Asia/Bangkok
    networks:
      - ipca-stack
    depends_on:
      - ipca-api

networks:
  ipca-stack:
    external: true
