services:
  ipca-frontend:
    container_name: ipca-frontend
    build:  
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    networks:
      - ipca-stack
    env_file:
      - .env

networks:
  ipca-stack:
    external: true
