services:
  ipca-frontend:
    container_name: ipca-frontend
    build: .
    restart: on-failure
    networks:
      - ipca-stack
      - tunnel
    env_file:
      - .env

networks:
  ipca-stack:
    external: true
