services:
  ipca-frontend:
    container_name: ipca-frontend
    context: .
    dockerfile: Dockerfile.prod
    restart: unless-stopped
    networks:
      - ipca-stack
    env_file:
      - .env

networks:
  ipca-stack:
    external: true
