name: Deploy Backend

on:
  push:
    branches: ["master", "dev"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ github.ref == 'refs/heads/master' && 'ipca-prod' || 'ipca-test' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          # Backend
          echo "VITE_IPCA_API=${{ secrets.VITE_IPCA_API }}" >> .env
          
      - name: Deploy Web Application
        if: github.ref == 'refs/heads/master'
        run: docker compose -f docker-compose.prod.yml up -d --build --force-recreate && docker system prune -f

      - name: Deploy Web Application (Dev)
        if: github.ref == 'refs/heads/dev'
        run: docker compose -f docker-compose.dev.yml up -d --build --force-recreate && docker system prune -f
